{
  pkgs,
  ...
}
:
{
  wayland.windowManager.hyprland.settings.workspace = 
  [
      "10,monitor:DP-3,default:true"
      "11,monitor:DP-4,default:true"
      "1,monitor:eDP-1,default:true"
      "2,monitor:eDP-1"
      "3,monitor:eDP-1"
      "4,monitor:eDP-1"
      "5,monitor:eDP-1"
      "6,monitor:eDP-1"
      "7,monitor:eDP-1"
      "8,monitor:eDP-1"
      "9,monitor:eDP-1"
  ];
}
